FORMAT: 1A
HOST: https://api.mail-list.com

# Mail-List.com API
Add, Change or Delete your members from your mailing list(s) at Mail-List.com

Version 1 acts against just one mailing list, and uses the list name and password as authetication.

All commands include these headers

   + Headers

        x-mail-list-version: 1
        x-mail-list-list-name: example-list
        x-mail-list-password: 12345

Version 2 acts against all mailing lists for a given client, and uses an API key as authentication.

# Group Members of one particular Mailing List

## Members Collection [/members]
### List All Members [GET]
+ Response 200 (application/json)

        [
            {
                "email_address":
                  [
                      "joe@gmail.com",
                      "sally@outlook.com",
                      "bob@yahoo.com"
                  ]
            }
        ]


# Group Member of particular Mailing List
## Member Entity [/member/{?email_address}]
### Check For Specific Member [GET]
+ Parameters
    + email_address: joe%40gmail.com (string) - An email address for identifier
+ Response 200 (application/json)

        {
            "email_address": "joe@gmail.com"
        }


### Delete a Member [DELETE]
+ Request (application/json)
+ Parameters
    + email_address: joe%40gmail.com (string) - An email address for identifier
+ Response 200

### Add a New Member [POST]
+ Request (application/json)

        { "email_address": "joe@gmail.com" }

+ Response 201


### Change a Member to a different email address [PUT]
+ Request (application/json)

        { "email_address": "joe@aol.com" }
    
+ Response 200 (application/json)

        {
            "email_address": "joe@aol.com"
        }
